### PR TITLE
RDF n(r) Normalization

### LINKED ISSUE #1037: Cumulative RDF is incorrect for different arrays
### Description

The cumulative RDF (`RDF.n_r`) does not give the expected values if different arrays are used for the system & query points, and the arrays don't have the same shape.

I think that in this line:
https://github.com/glotzerlab/freud/blob/aa7f09a9716290172dd3bb3e764164ef4479dea4/cpp/density/RDF.cc#L77
the prefactor should use the number of query points rather than system points, so that the average is taken over query points.

### Steps to Reproduce

```python
import numpy as np
import freud                                                                         

L = 12. 
box = freud.Box.from_box([L, L, L])
rdf = freud.density.RDF(10, 5.)

rng = np.random.default_rng()
ri = L*rng.uniform(low=-0.5, high=0.5, size=(10, 3))                                 
rj = L*rng.uniform(low=-0.5, high=0.5, size=(20, 3))                                 

# same
rdf.compute(system=(box, ri), query_points=ri)
n_r = np.cumsum(rdf.bin_counts/ri.shape[0])
print(np.allclose(n_r, rdf.n_r))

# different
rdf.compute(system=(box, rj), query_points=ri)
n_r = np.cumsum(rdf.bin_counts/ri.shape[0])
print(np.allclose(n_r, rdf.n_r))
```

### Error Output

```shell
Current output is:

True
False

but it should be:

True
True
```

### freud Version

v2.11.0

### Python Version

v3.10.5

### System Platform

Linux

### Installation method

Download from conda-forge

### Developer

Would someone else please fix this?

### PR DESCRIPTION
**Pull request by tommy-waltmann**
## Description

The cumulative bin counts function, n(r), was using the set of points to average the data, not the set of query points.

## Motivation and Context
Resolves: #1037 

## How Has This Been Tested?

I have fixed an existing test which was implemented wrong.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

File: cpp/density/RDF.cc [hunk 1]
```diff
@@ -58,7 +58,8 @@ void RDF::reduce()
     m_N_r.prepare(getAxisSizes()[0]);
 
     // Define prefactors with appropriate types to simplify and speed later code.
-    float number_density = float(m_n_query_points) / m_box.getVolume();
+    auto nqp = static_cast<float>(m_n_query_points);
```
Comment (vyasr) [inline cpp/density/RDF.cc]:
```suggestion
    auto const nqp = static_cast<float>(m_n_query_points);
```

**Review by vyasr — APPROVED** [review]
Fix looks great, thanks!
