### PR TITLE
Sphere Voxelization

### LINKED ISSUE #209: Improve support for aperiodic boxes / boundary conditions
Almost all systems that we analyze are periodic in all of their 2 or 3 dimensions. However, not all methods in `freud` support boxes that are aperiodic in one or more dimensions.

- [ ] Survey modules and determine which ones do/don't fully support aperiodicity
- [ ] Write tests to check for aperiodic behavior
- [ ] Fix failing tests by adding support for aperiodic behavior

### LINKED ISSUE #610: Ambiguous widths/dimensionality in GaussianDensity
In `GaussianDensity` and `SphereVoxelization`, the `width` variable in C++ is a copy of `m_width` but with z=1 if a 2D box is provided. This allows users to specify an integer for all dimensions, but it makes the behavior of `width` a bit ambiguous. If the user inputs `width=100` in the constructor, the `width` property returns `[100, 100, 100]` regardless of the dimensionality of the input system's box.

### LINKED ISSUE #611: GaussianDensity does not normalize correctly in 2D.
**Describe the bug**
The gaussian normalization factor for 2D systems is incorrect in GaussianDensity. It uses the normalization that would be appropriate for 3D systems. The formula should be:
fcab90af48acc1ff0f5076815cfb8022

This will be resolved by #606 and is now tested for validity, this issue exists to make a note for posterity.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR adds a new feature for "voxelization," which is similar to GaussianDensity in that it produces a 2D or 3D "image" from a set of points. A user provides a set of points, an output size, and a radius, which is used to create a voxel grid where each voxel is a 1 if it is within `radius` of one or more of the provided points, and 0 otherwise.

This PR also extends the periodicity logic in freud to allow for aperiodic calculations in GaussianDensity and Voxelization. e.g. If the box is aperiodic, then a point on the left edge of the box will not wrap and fill voxels on the right edge.

**This PR supercedes #573.**

## Motivation and Context
This feature is useful for producing image-like data from point configurations, which I plan to use for input to a machine learning algorithm.

## How Has This Been Tested?
New tests have been added.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [credits](https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst).
- [x] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

**Review by tommy-waltmann — APPROVED** [review]
I think this is good to go.

File: cpp/density/SphereVoxelization.cc [hunk 1]
```diff
@@ -0,0 +1,142 @@
+// Copyright (c) 2010-2019 The Regents of the University of Michigan
+// This file is from the freud project, released under the BSD 3-Clause License.
+
+#include <cmath>
+#include <stdexcept>
+#include <tbb/tbb.h>
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc]: Need to replace with specific tbb headers (see #605).

File: cpp/density/SphereVoxelization.cc [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+//! internal
+/*! \brief Function to compute the voxels array
+ */
+void SphereVoxelization::compute(const freud::locality::NeighborQuery* nq)
+{
+    auto box = nq->getBox();
+    auto n_points = nq->getNPoints();
+    m_box = box;
+
+    vec3<unsigned int> width(m_width);
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc]: Could this variable be removed and replaced by `m_width` everywhere?

File: cpp/density/SphereVoxelization.cc [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+}
+
+//! internal
+/*! \brief Function to compute the voxels array
+ */
+void SphereVoxelization::compute(const freud::locality::NeighborQuery* nq)
+{
+    auto box = nq->getBox();
+    auto n_points = nq->getNPoints();
+    m_box = box;
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc]: Replace uses of `box` with `m_box`.
```suggestion
    m_box = nq->getBox();
    auto n_points = nq->getNPoints();
```

File: cpp/density/SphereVoxelization.cc [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+            const int bin_x = int((point.x + lx / 2.0f) / grid_size_x);
+            const int bin_y = int((point.y + ly / 2.0f) / grid_size_y);
+            // In 2D, only loop over the z=0 plane
+            const int bin_z = m_box.is2D() ? 0 : int((point.z + lz / 2.0f) / grid_size_z);
+
+            // Reject bins that are outside the box in aperiodic directions
+            // Only evaluate over bins that are within the cutoff
+            for (int k = bin_z - bin_cut_z; k <= bin_z + bin_cut_z; k++)
+            {
+                if (!periodic.z && (k < 0 || k >= int(m_width.z)))
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc:93]: I would like to see this conditional logic structure replicated in `GaussianDensity`. It should be faster to evaluate and reject the inner loops in advance.

File: cpp/density/SphereVoxelization.cc [hunk 5]
```diff
@@ -0,0 +1,142 @@
...
+                        // Check to see if this distance is within the specified r_max
+                        if (r_sq < r_max_sq)
+                        {
+                            // Assure that out of range indices are corrected for storage
+                            // in the array i.e. bin -1 is actually bin 29 for nbins = 30
+                            const unsigned int ni = (i + m_width.x) % m_width.x;
+                            const unsigned int nj = (j + m_width.y) % m_width.y;
+                            const unsigned int nk = (k + m_width.z) % m_width.z;
+
+                            m_voxels_array(ni, nj, nk) = 1;
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc:131]:
```suggestion
                            // This array value could be written by multiple threads in parallel.
                            // This is only safe because all threads are writing the same value (1).
                            m_voxels_array(ni, nj, nk) = 1;
```

File: cpp/density/SphereVoxelization.cc [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+                        }
+                    }
+                }
+            }
+        }
+    });
+
+    // Now reduce all the arrays into one.
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc]: Remove this commented section.

File: cpp/density/SphereVoxelization.h [hunk 7]
```diff
@@ -0,0 +1,63 @@
+// Copyright (c) 2010-2019 The Regents of the University of Michigan
```
Comment (bdice) [inline cpp/density/SphereVoxelization.h]: Make sure all the copyrights are updated (see #602).
```suggestion
// Copyright (c) 2010-2020 The Regents of the University of Michigan
```

File: freud/density.pyx [hunk 8]
```diff
@@ -301,6 +301,117 @@ cdef class GaussianDensity(_Compute):
             return None
 
 
+cdef class SphereVoxelization(_Compute):
+    R"""Computes the integer density of a system on a grid.
```
Comment (bdice) [inline freud/density.pyx]:
```suggestion
    R"""Computes a grid of voxels occupied by spheres placed on a set of points.
```

File: freud/density.pyx [hunk 9]
```diff
@@ -301,6 +301,117 @@ cdef class GaussianDensity(_Compute):
...
+
+    Replaces particle positions with a sphere of fixed radius and calculates the
+    contribution from each to the proscribed grid based upon the distance of
+    the grid cell from the center of the sphere. The resulting data is a
+    regular grid of particle densities with an integer for each grid cell that
+    indicates the number of particles whose spheres overlap that cell. The
```
Comment (bdice) [inline freud/density.pyx]: This isn't true -- it's not a number of particles, it's always a 0 or 1 state.

File: freud/density.pyx [hunk 10]
```diff
@@ -301,6 +301,117 @@ cdef class GaussianDensity(_Compute):
...
+    dimensions of the image (grid) are set in the constructor, and can either
+    be set equally for all dimensions or for each dimension independently.
+
+    Args:
+        width (int or list or tuple):
+            The number of bins to make the image in each direction (identical
+            in all dimensions if a single integer value is provided).
```
Comment (bdice) [inline freud/density.pyx]: Also make these changes for GaussianDensity.
```suggestion
        width (int or Sequence[int]):
            The number of bins to make the image in each dimension (identical
            in all dimensions if a single integer value is provided).
```

File: freud/density.pyx [hunk 11]
```diff
@@ -301,6 +301,117 @@ cdef class GaussianDensity(_Compute):
...
+    @property
+    def r_max(self):
+        """float: Sphere radius used for voxelization."""
+        return self.thisptr.getRMax()
+
+    @property
+    def width(self):
+        """int or list or tuple: The number of bins to make the image in each
+        direction (identical in all dimensions if a single integer value is
+        provided)."""
```
Comment (bdice) [inline freud/density.pyx]: Also apply this fix to GaussianDensity.
```suggestion
        """tuple[int]: The number of bins in the image in each dimension
        (identical in all dimensions if a single integer value is
        provided)."""
```

**Review by bdice — COMMENTED** [review]
@tommy-waltmann I have some comments. Would you be able to take a look at these?

File: cpp/density/SphereVoxelization.cc (hunk 1 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: There is no explicit tbb in this file, so if I understand correctly, these need to be the tbb headers required for forLoopWrapper, right?

File: cpp/density/SphereVoxelization.cc (hunk 2 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: I think so. It looks like later in the method we go back to using `m_width` anyway. Do you remember what the original intent of defining the `width` variable was?

Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: Looks like its from `GaussianDensity`, do you remember the original intent of defining things this way?

File: cpp/density/SphereVoxelization.cc (hunk 4 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc:93]: I concur

File: cpp/density/SphereVoxelization.cc (hunk 2 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: It turns out it is necessary, I'm not exactly sure why, other than in the 2D case, `m_voxels_array` ends up being 3 dimensional instead of 2

Comment (bdice) [reply cpp/density/SphereVoxelization.cc]: This currently isn't a great design. The `width` variable is a copy of `m_width` but with z=1 if a 2D box is provided. This allows users to specify an integer for all dimensions, but it makes the behavior a bit ambiguous. If the user inputs `width=100` in the constructor, the `width` property returns `[100, 100, 100]` regardless of what dimensionality the box has... I'm not sure what to do about this but we can raise an issue.

Comment (bdice) [reply cpp/density/SphereVoxelization.cc]: See #610. Closing this conversation for now -- this can be resolved later in a way that is consistent for GaussianDensity and SphereVoxelization.

File: cpp/density/GaussianDensity.cc [hunk 12]
```diff
@@ -81,44 +81,51 @@ void GaussianDensity::compute(const freud::locality::NeighborQuery* nq)
...
                         {
-                            // Evaluate the gaussian ...
-                            const float x_gaussian
-                                = A * std::exp((-1.0f) * (delta.x * delta.x) / (2.0f * sigmasq));
-                            const float y_gaussian
-                                = A * std::exp((-1.0f) * (delta.y * delta.y) / (2.0f * sigmasq));
-                            const float z_gaussian
-                                = A * std::exp((-1.0f) * (delta.z * delta.z) / (2.0f * sigmasq));
+                            // Evaluate the gaussian
+                            const float gaussian = A * std::exp(-r_sq / (2 * sigmasq));
```
Comment (bdice) [inline cpp/density/GaussianDensity.cc]: There is a bug in the Gaussian normalization in the old code for 2D systems. I am adding a separate changelog line to address that.

**Comment by vyasr** [comment]
I see that I'm assigned on here, I won't be able to review until mid-week but will plan to review around Wednesday.

File: benchmarks/benchmark_density_GaussianDensity.py [hunk 13]
```diff
@@ -27,7 +27,7 @@ def bench_run(self, N):
 def run():
     Ns = [1000, 10000]
     width = 100
-    r_max = 10
+    r_max = 1
```
Comment (vyasr) [inline benchmarks/benchmark_density_GaussianDensity.py:30]: Why were these changes made? They seem unrelated to everything else, is there a compelling reason to use different parameters?

File: cpp/box/Box.h [hunk 14]
```diff
@@ -295,10 +295,25 @@ class Box
...
+            v_frac.x = util::modulusPositive(v_frac.x, 1.0f);
+        }
+        if (m_periodic.y)
+        {
+            v_frac.y = util::modulusPositive(v_frac.y, 1.0f);
+        }
+        if (m_periodic.z)
+        {
+            v_frac.z = util::modulusPositive(v_frac.z, 1.0f);
+        }
```
Comment (vyasr) [inline cpp/box/Box.h:316]: While this wrapping logic is correct, the discussion in #209 suggests that there are cases where it won't work. However, on further consideration I'm not sure that this is the case; do we ever wrap positions? AFAIK we only ever need to wrap vectors between two points, not vectors representing a point. @bdice let's make sure this is true before we merge this change since it will immediately make it possible for classes to operate on aperiodic boxes even if the behavior isn't quite correct. Also, are there any cases where we would need to disable that behavior?

File: cpp/density/GaussianDensity.cc [hunk 15]
```diff
@@ -31,94 +31,107 @@ vec3<unsigned int> GaussianDensity::getWidth()
...
 
-//! internal
-/*! \brief Function to compute the density array
- */
+//! Compute the density array.
 void GaussianDensity::compute(const freud::locality::NeighborQuery* nq)
 {
-    auto box = nq->getBox();
+    // Don't allow 3D boxes after computing in 2D (m_width is altered)
+    if (!nq->getBox().is2D() && m_box.is2D())
```
Comment (vyasr) [inline cpp/density/GaussianDensity.cc]: Should we also forbid the other direction, i.e. 
```suggestion
    if (nq->getBox().is2D() != m_box.is2D())
```
?

File: cpp/box/Box.h (hunk 14 above)
Comment (vyasr) [reply cpp/box/Box.h:316]: To be clear, while I think making the rest of freud work for aperiodic systems is out of scope for this PR, if we're introducing this change I think we do at least need to add error messages everywhere that aperiodic boxes could break the logic before this PR can be merged.

File: cpp/density/GaussianDensity.cc [hunk 16]
```diff
@@ -31,94 +31,107 @@ vec3<unsigned int> GaussianDensity::getWidth()
...
                         {
-                            // Evaluate the gaussian ...
-                            const float x_gaussian
-                                = A * std::exp((-1.0f) * (delta.x * delta.x) / (2.0f * sigmasq));
-                            const float y_gaussian
-                                = A * std::exp((-1.0f) * (delta.y * delta.y) / (2.0f * sigmasq));
-                            const float z_gaussian
-                                = A * std::exp((-1.0f) * (delta.z * delta.z) / (2.0f * sigmasq));
+                            // Evaluate the gaussian
+                            const float gaussian = normalization * std::exp(-r_sq / (2 * sigmasq));
```
Comment (vyasr) [inline cpp/density/GaussianDensity.cc]:
```suggestion
                            const float gaussian = normalization * std::exp(-r_sq / (float(2.0) * sigmasq));
```

File: cpp/density/SphereVoxelization.cc [hunk 17]
```diff
@@ -0,0 +1,131 @@
...
+namespace freud { namespace density {
+
+SphereVoxelization::SphereVoxelization(vec3<unsigned int> width, float r_max)
+    : m_box(box::Box()), m_width(width), m_r_max(r_max)
+{
+    if (r_max <= 0.0f)
+        throw std::invalid_argument("SphereVoxelization requires r_max to be positive.");
+}
+
+//! Get a reference to the last computed voxels
```
Comment (vyasr) [inline cpp/density/SphereVoxelization.cc]:
```suggestion
//! Get a reference to the last computed voxels.
```

File: cpp/density/SphereVoxelization.cc [hunk 18]
```diff
@@ -0,0 +1,131 @@
...
+        {
+            const vec3<float> point = (*nq)[idx];
+            // Find which bin the particle is in
+            const int bin_x = int((point.x + Lx / 2.0f) / grid_size_x);
+            const int bin_y = int((point.y + Ly / 2.0f) / grid_size_y);
+            // In 2D, only loop over the z=0 plane
+            const int bin_z = m_box.is2D() ? 0 : int((point.z + Lz / 2.0f) / grid_size_z);
+
+            // Reject bins that are outside the box in aperiodic directions
+            // Only evaluate over bins that are within the cutoff
```
Comment (vyasr) [inline cpp/density/SphereVoxelization.cc]:
```suggestion
            // Only evaluate over bins that are within the cutoff, rejecting bins
            // that are outside the box in aperiodic directions.
```

File: cpp/util/utils.h [hunk 19]
```diff
@@ -47,34 +48,59 @@ inline void forLoopWrapper(size_t begin, size_t end, const Body& body, bool para
...
+            [&body](const tbb::blocked_range3d<size_t>& r) {
+                body(r.pages().begin(), r.pages().end(), r.rows().begin(), r.rows().end(), r.cols().begin(),
+                     r.cols().end());
+            });
+    }
+    else
+    {
+        body(begin_page, end_page, begin_row, end_row, begin_col, end_col);
+    }
+}
```
Comment (vyasr) [inline cpp/util/utils.h]: Let's remove this function. We can add it at a later date if we have a need for it, but we have enough experience with how long cruft lies around in freud that I don't want to carry around unused functions without a demonstrated need. Also remove the corresponding blocked_range3d include at the top.

File: doc/source/reference/credits.rst [hunk 20]
```diff
@@ -101,6 +101,9 @@ Bradley Dice - **Lead developer**
 * Added finite tolerance to ensure stability of 2D Voronoi NeighborList computations.
 * Improved stability of Histogram bin calculations.
 * Improved error handling of Cubatic input parameters.
+* Added SphereVoxelization feature.
```
Comment (vyasr) [inline doc/source/reference/credits.rst]:
```suggestion
* Worked with Tommy Waltmann to add the SphereVoxelization feature.
```

File: doc/source/reference/credits.rst [hunk 21]
```diff
@@ -285,6 +288,10 @@ Mike Henry
 * Fixed syntax in freud-examples notebooks for v2.0.
 * Updated documentation links
 
+Tommy Waltmann
+
+* Added SphereVoxelization feature.
```
Comment (vyasr) [inline doc/source/reference/credits.rst]:
```suggestion
* Worked with Bradley Dice to add the SphereVoxelization feature.
```

File: freud/_density.pxd [hunk 22]
```diff
@@ -57,3 +57,13 @@ cdef extern from "RDF.h" namespace "freud::density":
...
         const freud.util.ManagedArray[float] &getNr()
+
+cdef extern from "SphereVoxelization.h" namespace "freud::density":
+    cdef cppclass SphereVoxelization:
+        SphereVoxelization(vec3[unsigned int], float) except +
+        const freud._box.Box & getBox() const
+        void reset()
+        void compute(const freud._locality.NeighborQuery*) except +
+        const freud.util.ManagedArray[unsigned int] &getVoxels() const
+        vec3[unsigned int] getWidth() const
```
Comment (vyasr) [inline freud/_density.pxd:68]:
```suggestion
        vec3[unsigned int] getWidth() const
```

File: cpp/density/SphereVoxelization.h [hunk 23]
```diff
@@ -0,0 +1,65 @@
...
+        return m_r_max;
+    }
+
+    //! Compute the voxelization.
+    void compute(const freud::locality::NeighborQuery* nq);
+
+    //! Get a reference to the last computed voxels.
+    const util::ManagedArray<unsigned int>& getVoxels() const;
+
+    vec3<unsigned int> getWidth();
```
Comment (vyasr) [inline cpp/density/SphereVoxelization.h]:
```suggestion
    vec3<unsigned int> getWidth() const;
```

File: cpp/density/SphereVoxelization.cc [hunk 24]
```diff
@@ -0,0 +1,131 @@
...
+}
+
+//! Get a reference to the last computed voxels
+const util::ManagedArray<unsigned int>& SphereVoxelization::getVoxels() const
+{
+    return m_voxels_array;
+}
+
+//! Get width.
+vec3<unsigned int> SphereVoxelization::getWidth()
```
Comment (vyasr) [inline cpp/density/SphereVoxelization.cc]:
```suggestion
vec3<unsigned int> SphereVoxelization::getWidth() const
```

**Review by vyasr — CHANGES_REQUESTED** [review]
This looks pretty good, I have some inline requests but mostly nothing too major, the one possible exception being the consideration of how to handle aperiodic boxes now that they've been introduced. We also need to add tests of the box wrapping logic now that it's supporting aperiodic cases. I'd also like to see at least one test of the new voxelization that actually tests its behavior, either something like the PMFT tests where the bin counts are validated using an equivalent Python method or at the very least a known system where the counts can be stored, perhaps something generated with `freud.data.make_alternating_lattice` or similar.

File: cpp/density/SphereVoxelization.cc (hunk 24 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: What is the need for the first `const` here? This returns a copy of `m_width`, meaning the user can't modify the data in the in the `SphereVoxelization` class, so why do we care whether or not the user can change the returned copy?

**Comment by tommy-waltmann** [comment]
> 
> 
> This looks pretty good, I have some inline requests but mostly nothing too major, the one possible exception being the consideration of how to handle aperiodic boxes now that they've been introduced. We also need to add tests of the box wrapping logic now that it's supporting aperiodic cases. I'd also like to see at least one test of the new voxelization that actually tests its behavior, either something like the PMFT tests where the bin counts are validated using an equivalent Python method or at the very least a known system where the counts can be stored, perhaps something generated with `freud.data.make_alternating_lattice` or similar.

I implemented an fft version of the aperiodic voxelization for my photonics project with Bradley (we found that it was too slow and aren't going to use it), so I can add test case(s) that will serve as a cross-check for the actual behavior of SphereVoxelization.

File: cpp/density/GaussianDensity.cc (hunk 16 above)
Comment (tommy-waltmann) [reply cpp/density/GaussianDensity.cc]: The variable `sigmasq` is a float, so what is the need for casting here? Also, isn't casting in cpp done as `(float) 2.0`, not `float(2.0)`?

Comment (vyasr) [reply cpp/density/GaussianDensity.cc]: You're mostly right about these two things. The `(float) 2.0` style is actually C-style casting, not C++ style. The function style cast `float(2.0)` was added in C++, but it behaves exactly like C-style casts except in cases where there are multiple arguments, in which case it is capable of calling more complex constructors.

The preferred method of casting in C++ is actually by explicitly specifying the type of the cast, in this case `static_cast` (https://en.cppreference.com/w/cpp/language/static_cast). 
C-style casts are pretty unsafe in general since they will even try to cast things that aren't safe to cast to each other. However, in cases like this where the object is a float literal I don't personally worry about that. If we wanted to *strictly* adhere to best practices we would want to go through the entire code base and replace most such casts with the `static_cast` variant, but there's not really a good reason to.

You're also right that casting isn't strictly necessary here. The reason I made the change is in anticipation of a future release of freud that supports variable/mixed precision (see #464). The easiest way to do that is something like what HOOMD does, where there's a global typedef of the desired type (`Scalar` in HOOMD) and all literals are typecast throughout the code base. This of course relies on compilers to optimize away the type conversion since otherwise you don't really get the same performance tradeoffs, but that's a pretty safe assumption in such simple cases AFAIK.

File: cpp/density/SphereVoxelization.cc (hunk 24 above)
Comment (vyasr) [reply cpp/density/SphereVoxelization.cc:29]: You are correct, this is a mistake on my part. Ignore this, as well as the corresponding suggestions on the pxd file.

Comment (vyasr) [reply cpp/density/SphereVoxelization.cc]: You are correct. For future reference, I had accidentally added a const qualifier to the return type, which is meaningless here. In the interest of being able to batch commit these suggestions, I've updated the suggestion here, in the header, and in the corresponding pxd file.

**Comment by vyasr** [comment]
Thanks Tommy. I fixed a couple errors you caught in my review, and the test you added generally looks good. I'll give this another pass once Bradley applies my changes, then I think we should be good to go.

File: cpp/density/GaussianDensity.cc (hunk 15 above)
Comment (tommy-waltmann) [reply cpp/density/GaussianDensity.cc]: We should have each instance of `SphereVoxelization` and `GaussianDensity` only perform the calculation in a single number of dimensions. It removes the ambiguity of what is and isn't allowed in terms of going between numbers of dimensions between calculations and prevents any unseen errors associated with that that we might be missing.

File: cpp/density/SphereVoxelization.cc [hunk 25]
```diff
@@ -0,0 +1,145 @@
...
+*/
+
+namespace freud { namespace density {
+
+SphereVoxelization::SphereVoxelization(vec3<unsigned int> width, float r_max)
+    : m_width(width), m_r_max(r_max)
+{
+    // dummy initial box, dimensionality of the calculation will be defined by
+    // the first neighbor query passed to the compute method
+    m_box = NULL;
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc]: I support the idea of preventing dimensionality changes in either direction, but I am not sure `NULL` is the right strategy here. Honestly I have no idea how `m_box` would act after initializing it to `NULL`.

`NULL` is not recommended for use in C++11 or newer. https://stackoverflow.com/questions/55520687/is-null-a-pointer

[`nullptr`](https://en.cppreference.com/w/cpp/language/nullptr) is the preferred way to use null pointers, but `m_box` _isn't a pointer_. 

I would rather keep a flag like `bool m_has_computed` that is used when checking the "new" box dimensionality against the stored box dimensionality.

File: cpp/density/SphereVoxelization.cc [hunk 26]
```diff
@@ -0,0 +1,145 @@
...
+
+    // Don't allow changes in the number of dimensions for the calculation
+    // after its been set.
+    if (nq->getBox().is2D() != m_box.is2D())
+    {
+        throw std::invalid_argument(
+            "Each SphereVoxelization instance should be used to do calculations "
+            "in a fixed number of dimensions. You have changed the number of "
+            "dimensions used going from one calculation to another.");
+    }
```
Comment (bdice) [inline cpp/density/SphereVoxelization.cc]: With my comment above, this would become the following. Note that error messages should avoid using second-person "you" in their text. It sounds less accusatory that way. 😉
```suggestion
    // Set the number of dimensions for the calculation the first time it is done
    if (!m_has_computed || nq->getBox().is2D() != m_box.is2D())
    {
        m_box = nq->getBox();
        m_has_computed = true;
    } else {
        throw std::invalid_argument(
            "The dimensionality of the box passed to SphereVoxelization has changed. "
            "A new instance must be created to handle a different dimensionality.");
    }
```

Comment (bdice) [reply cpp/density/SphereVoxelization.cc]: And remove the second assignment of `m_box` below, as needed. And make GaussianDensity match.

File: cpp/density/SphereVoxelization.cc (hunk 25 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: I agree with switching this to `nullptr`, but the class is designed such that nothing can happen before `compute()` is called, so I don't think we have to worry about how `m_box` acts after setting it to `nullptr` because the first thing that happens in `compute()` is that we set `m_box` to something that isn't `nullptr`.

Comment (bdice) [reply cpp/density/SphereVoxelization.cc]: To clarify, I wasn’t recommending to use nullptr for this case. You should not assign a pointer type to m_box because it isn’t a pointer. I would like to be explicit with the m_has_computed flag. The m_box should be default-constructed and the flag should track its assignment. That’s a much safer approach.

File: cpp/density/SphereVoxelization.cc (hunk 26 above)
Comment (tommy-waltmann) [reply cpp/density/SphereVoxelization.cc]: I think the boolean condition in the if statement here should read `!m_has_computed || nq->getBox().is2D() == m_box.is2D()`

Comment (bdice) [reply cpp/density/SphereVoxelization.cc]: Right. Good catch.

File: cpp/util/utils.h (hunk 19 above)
Comment (tommy-waltmann) [reply cpp/util/utils.h]: I don't think this is within scope of the PR, I agree that the change should be made, but let's do this somewhere else.

Comment (vyasr) [reply cpp/util/utils.h]: @tommy-waltmann I'm not sure I follow your logic. This function is being added by this PR, so choosing _not_ to add it definitely seems in scope for this PR.

File: cpp/box/Box.h (hunk 14 above)
Comment (tommy-waltmann) [reply cpp/box/Box.h:316]: I'm unfamiliar with many of the calculations in freud right now, did you have any in mind specifically that could benefit from this type of error message?

File: cpp/density/GaussianDensity.cc [hunk 27]
```diff
@@ -31,94 +31,116 @@ vec3<unsigned int> GaussianDensity::getWidth()
...
+    if (!m_has_computed || nq->getBox().is2D() == m_box.is2D())
+    {
+        m_box = nq->getBox();
+        m_has_computed = true;
+    }
+    else
+    {
+        throw std::invalid_argument(
+            "The dimensionality of the box passed to GaussianDensity has "
+            "changed. A ne instance must be created to handle a different "
```
Comment (vyasr) [inline cpp/density/GaussianDensity.cc]:
```suggestion
            "changed. A new instance must be created to handle a different "
```

File: cpp/box/Box.h (hunk 14 above)
Comment (vyasr) [reply cpp/box/Box.h:316]: Offhand I'd say anything that touches neighbor finding, you wouldn't want to find periodic neighbors in an aperiodic box. So I would probably put errors in the `query` method of `NeighborQuery` (you might have to do it in the subclasses, I honestly can't remember if I made that method is pure virtual or not). I _think_ that all non-pair computations other than `GaussianDensity` (and now `SphereVoxelization`) should be safe because they just interact with the point positions or orientations. These two are special because the smearing requires accounting for periodicity, but I don't think any of the others do.

Comment (tommy-waltmann) [reply cpp/box/Box.h:316]: `query()` is not pure virtual, so I'll add an error there. That should be the only place where we have not already accounted for box periodicity right? In terms of docs updates for this, should a notice go in every pair calculation, or is there a separate place for this to go?

File: ChangeLog.md [hunk 28]
```diff
@@ -11,15 +11,18 @@ and this project adheres to
...
 ### Changed
 * Cython is now a required dependency (not optional). Cythonized `.cpp` files have been removed.
+* An instance of GaussianDensity cannot compute 3D systems if it has been previously computed 2D systems.
 
 ### Fixed
 * Histogram bin locations are computed in a more numerically stable way.
 * Improved error handling of Cubatic input parameters.
 * PMFTs are now properly normalized such that the pair correlation function tends to unity for an ideal gas.
 * PMFTXYT uses the correct orientations when points and query\_points differ.
+* GaussianDensity gaussian normalization in 2D systems has been corrected.
```
Comment (vyasr) [inline ChangeLog.md]:
```suggestion
* GaussianDensity Gaussian normalization in 2D systems has been corrected.
```

File: cpp/density/SphereVoxelization.cc [hunk 29]
```diff
@@ -0,0 +1,140 @@
...
+//! Get width.
+vec3<unsigned int> SphereVoxelization::getWidth() const
+{
+    return m_width;
+}
+
+//! Compute the voxels array.
+void SphereVoxelization::compute(const freud::locality::NeighborQuery* nq)
+{
+    // set the number of dimensions for the calculation the first time it is done
```
Comment (vyasr) [inline cpp/density/SphereVoxelization.cc]:
```suggestion
    // Set the number of dimensions for the calculation the first time it is done.
```

File: cpp/util/utils.h [hunk 30]
```diff
@@ -3,9 +3,10 @@
 
 #include <algorithm>
 #include <cmath>
-#include <tbb/parallel_for.h>
 #include <tbb/blocked_range.h>
 #include <tbb/blocked_range2d.h>
+#include <tbb/blocked_range3d.h>
+#include <tbb/parallel_for.h>
```
Comment (vyasr) [inline cpp/util/utils.h]:
```suggestion
#include <tbb/parallel_for.h>
```

File: freud/density.pyx [hunk 31]
```diff
@@ -301,6 +300,115 @@ cdef class GaussianDensity(_Compute):
...
+    either be set equally for all dimensions or for each dimension
+    independently.
+
+    Args:
+        width (int or Sequence[int]):
+            The number of bins to make the grid in each dimension (identical
+            in all dimensions if a single integer value is provided).
+        r_max (float):
+            Sphere radius.
+    """  # noqa: E501
```
Comment (vyasr) [inline freud/density.pyx]: I don't think there's any reason to request longer lines here, usually we only do this in the docstrings for classes where the argument type involves a long `:class:numpy.ndarray...` type (or similar) that overflows on a single line.
```suggestion
    """
```

File: tests/SphereVoxelization_fft.py [hunk 32]
```diff
@@ -0,0 +1,144 @@
...
+            True if the box should be considered periodic
+    """
+    eff_rad = r_max / box_size * width
+
+    # enlarge the box for the fft by adding more segments of the same length
+    # we will cut the extra off later so the fft will be aperiodic.
+    if periodic:
+        buf_size = 0
+    else:
+        buf_size = int(round(eff_rad + 1))
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    buf_size = 0 if periodic else int(round(eff_rad + 1))
```

File: tests/SphereVoxelization_fft.py [hunk 33]
```diff
@@ -0,0 +1,144 @@
...
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    buf_size = 0 if periodic else int(round(eff_rad + 1))
```

File: tests/SphereVoxelization_fft.py [hunk 34]
```diff
@@ -0,0 +1,144 @@
...
+    # set the overlaps to 1, instead of larger integers
+    np.clip(image, 0, 1, out=image)
+    return image
+
+
+def _put_points_on_grid(points, new_width, box_size, width, buf_size, ndim):
+    """
+    Creates a grid where the voxels are 1 if there is a point there (else 0)
+    """
+    d = tuple(new_width for _ in range(ndim))
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    d = (new_width, )*ndim
```

File: tests/SphereVoxelization_fft.py [hunk 35]
```diff
@@ -0,0 +1,144 @@
...
+    """
+    Does voxelization by doing an aperiodic fft of the sphere over the
+    points on the grid in 3 dimensions
+
+    Args:
+        box_size (float):
+            Length of the (assuemd cubic) box for the calculation.
+        width (int):
+            Number of grid spaces in each direction of the box
+        points (:np.ndarray: (N,3)):
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
        points (:np.ndarray: (N, 3)):
```

File: tests/SphereVoxelization_fft.py [hunk 36]
```diff
@@ -0,0 +1,144 @@
...
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
        points (:np.ndarray: (N, 3)):
```

File: tests/SphereVoxelization_fft.py [hunk 37]
```diff
@@ -0,0 +1,144 @@
...
+    # make the grid with the points on it
+    arr = _put_points_on_grid(points, new_width, box_size,
+                              width, buf_size, ndim=3)
+
+    # make the sphere
+    sphere = _make_sphere_3d(new_width, eff_rad)
+
+    # do the ffts
+    fft_arr = np.fft.fftn(arr)
+    fft_arr *= np.fft.fftn(sphere)
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    fft_arr = np.fft.fftn(arr) * np.fft.fftn(sphere)
```

File: tests/SphereVoxelization_fft.py [hunk 38]
```diff
@@ -0,0 +1,144 @@
...
+    # make the grid with the points on it
+    arr = _put_points_on_grid(points, new_width, box_size,
+                              width, buf_size, ndim=2)
+
+    # make the sphere
+    sphere = _make_sphere_2d(new_width, eff_rad)
+
+    # do the ffts
+    fft_arr = np.fft.fft2(arr)
+    fft_arr *= np.fft.fft2(sphere)
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    fft_arr = np.fft.fft2(arr) * np.fft.fft2(sphere)
```

File: tests/SphereVoxelization_fft.py [hunk 39]
```diff
@@ -0,0 +1,144 @@
...
+                      buf_size:-buf_size]
+
+    # set the overlaps to 1, instead of larger integers
+    np.clip(image, 0, 1, out=image)
+    return image
+
+
+def _put_points_on_grid(points, new_width, box_size, width, buf_size, ndim):
+    """
+    Creates a grid where the voxels are 1 if there is a point there (else 0)
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    Creates a grid where the voxels are 1 if there is a point there and 0 if not.
```

File: tests/SphereVoxelization_fft.py [hunk 40]
```diff
@@ -0,0 +1,144 @@
...
+    """
+    d = tuple(new_width for _ in range(ndim))
+    arr = np.zeros(d)
+    img_points = points / (box_size / width)  # points in units of grid spacing
+    for pt in img_points:
+        shifted_pt = list()
+        for i in range(ndim):
+            shifted_pt.append(int(round(pt[i])))
+        arr[tuple(shifted_pt)] = 1
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
        shifted_pt = tuple(int(round(pt[i])) for i in range(ndim))
        arr[shifted_pt] = 1
```

File: tests/SphereVoxelization_fft.py [hunk 41]
```diff
@@ -0,0 +1,144 @@
...
+    """
+    eff_rad = r_max / box_size * width
+
+    # enlarge the box for the fft by adding more segments of the same length
+    # we will cut the extra off later so the fft will be aperiodic.
+    if periodic:
+        buf_size = 0
+    else:
+        buf_size = int(round(eff_rad + 1))
+    new_width = 2*buf_size + width
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    new_width = 2 * buf_size + width
```

File: tests/SphereVoxelization_fft.py [hunk 42]
```diff
@@ -0,0 +1,144 @@
...
+        shifted_pt = list()
+        for i in range(ndim):
+            shifted_pt.append(int(round(pt[i])))
+        arr[tuple(shifted_pt)] = 1
+    return arr
+
+
+def _make_sphere_3d(new_width, eff_rad):
+    """makes a grid in 3D with voxels that are within eff_rad of the center
+    having value 1 (else 0)"""
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py]:
```suggestion
    """Makes a grid in 3D with voxels that are within ``eff_rad`` of the
    center having value 1 and other voxels having value 0."""
```

File: tests/SphereVoxelization_fft.py [hunk 43]
```diff
@@ -0,0 +1,144 @@
...
+    r_rad = int(round(eff_rad))
+    ctr = new_width // 2
+    arr = np.zeros((new_width, new_width, new_width))
+
+    for i in range(-r_rad, r_rad):
+        for j in range(-r_rad, r_rad):
+            for k in range(-r_rad, r_rad):
+                if np.linalg.norm([i, j, k]) < eff_rad:
+                    arr[ctr+i, ctr+j, ctr+k] = 1
```
Comment (vyasr) [inline tests/SphereVoxelization_fft.py:120]: Does this need to be modded by `new_width` like in `_make_sphere_2d` below?

File: cpp/density/SphereVoxelization.cc [hunk 44]
```diff
@@ -0,0 +1,140 @@
...
+#include "SphereVoxelization.h"
+
+/*! \file SphereVoxelization.cc
+    \brief Routines for computing voxelized densities from spheres centered at points.
+*/
+
+namespace freud { namespace density {
+
+SphereVoxelization::SphereVoxelization(vec3<unsigned int> width, float r_max)
+    : m_box(box::Box()), m_width(width), m_r_max(r_max), m_has_computed(false)
```
Comment (vyasr) [inline cpp/density/SphereVoxelization.cc]:
```suggestion
    : m_box(), m_width(width), m_r_max(r_max), m_has_computed(false)
```

File: cpp/density/GaussianDensity.cc [hunk 45]
```diff
@@ -13,7 +13,7 @@
 namespace freud { namespace density {
 
 GaussianDensity::GaussianDensity(vec3<unsigned int> width, float r_max, float sigma)
-    : m_box(box::Box()), m_width(width), m_r_max(r_max), m_sigma(sigma)
+    : m_box(box::Box()), m_width(width), m_r_max(r_max), m_sigma(sigma), m_has_computed(false)
```
Comment (vyasr) [inline cpp/density/GaussianDensity.cc]:
```suggestion
    : m_box(), m_width(width), m_r_max(r_max), m_sigma(sigma), m_has_computed(false)
```

**Review by vyasr — CHANGES_REQUESTED** [review]
@tommy-waltmann this is almost ready. I have a number of comments, but I think all but one of them can be applied directly (assuming you agree with them). The one open question I had is I think in the validation testing of SphereVoxelization, specifically in your reference implementation.

File: tests/SphereVoxelization_fft.py (hunk 43 above)
Comment (tommy-waltmann) [reply tests/SphereVoxelization_fft.py:120]: Under the assumption that the radius is smaller than half the size of the grid, the mod isn't really necessary, and if that assumption doesn't hold, the calculation doesn't even make much sense. I don't remember why I thought it would be necessary to put the mod in `_make_sphere_2d`, but upon closer inspection it shouldn't be necessary and might hide errors if it is left there, so I'm going to remove it.

Comment (bdice) [reply tests/SphereVoxelization_fft.py:120]: The original motivation was that I was experimenting with centering the sphere at `(0, 0)` instead of `(width//2, width//2)`. It's safe to remove.

File: benchmarks/benchmark_density_GaussianDensity.py (hunk 13 above)
Comment (tommy-waltmann) [reply benchmarks/benchmark_density_GaussianDensity.py:30]: @bdice I don't remember why these were changed, do you?

Comment (bdice) [reply benchmarks/benchmark_density_GaussianDensity.py:30]: There are two ratios, `r_max/L` and `sigma/r_max` that were somewhat unrealistic for practical use, AND the benchmark was taking too long.

Previously, `sigma=0.1` and `r_max=10` meant that `sigma/r_max` was very small, and the contributions near `r=r_max` were at the 100-sigma limit of a normal distribution (effectively zero). Changing that ratio to `sigma/r_max=10` is much more realistic. In practice it's fine to use an even lower value like 3, just depends on how precisely the integral over all grid spaces needs to get to 1. The tests in this PR explicitly check this normalization, which is related to issue #611.

The other relevant ratio is `r_max/L`, which was previously `3.1`. This meant that every point's Gaussian is contributing to (and being computed for) an extremely large proportion of grid cells. Like `4/3 * pi * (1/3.1)**3 = 0.1406`. That's not really how I've seen GaussianDensity used. I assumed a system of 10x10x10 particles in a simple cubic lattice, where every particle has a diameter of 1 (radius 0.5, diameter is equivalent to 10 bin widths since `width=100`).

**Review by vyasr — APPROVED** [review]
LGTM!
